export const timeZoneList = [
    {
        zone: {
            code: 'Africa', name: '非洲'
        },
        region: [
            { code: 'Africa/Abidjan', name: '阿比让' },
            { code: 'Africa/Accra', name: '阿克拉' },
            { code: 'Africa/Algiers', name: '阿尔及尔' },
            { code: 'Africa/Bissau', name: '比绍' },
            { code: 'Africa/Cairo', name: '开罗' },
            { code: 'Africa/Casablanca', name: '卡萨布兰卡' },
            { code: 'Africa/Ceuta', name: '休达' },
            { code: 'Africa/El_Aaiun', name: '阿尤恩' },
            { code: 'Africa/Johannesburg', name: '约翰内斯堡' },
            { code: 'Africa/Juba', name: '朱巴' },
            { code: 'Africa/Khartoum', name: '喀土穆' },
            { code: 'Africa/Lagos', name: '拉各斯' },
            { code: 'Africa/Maputo', name: '马普托' },
            { code: 'Africa/Monrovia', name: '蒙罗维亚' },
            { code: 'Africa/Nairobi', name: '内罗毕' },
            { code: 'Africa/Ndjamena', name: '恩贾梅纳' },
            { code: 'Africa/Sao_Tome', name: '圣多美' },
            { code: 'Africa/Tripoli', name: '的黎波里' },
            { code: 'Africa/Tunis', name: '突尼斯' },
            { code: 'Africa/Windhoek', name: '温得和克' },
        ]
    },
    {
        zone: { code: 'America', name: '美洲' },
        region: [
            { code: 'America/Adak', name: '亚达克' },
            { code: 'America/Anchorage', name: '安克雷奇' },
            { code: 'America/Araguaina', name: '阿拉瓜纳' },
            { code: 'America/Argentina/Buenos_Aires', name: '布宜诺斯艾利斯' },
            { code: 'America/Argentina/Catamarca', name: '卡塔马卡' },
            { code: 'America/Argentina/Cordoba', name: '科尔多瓦' },
            { code: 'America/Argentina/Jujuy', name: '朱伊' },
            { code: 'America/Argentina/La_Rioja', name: '里奥哈' },
            { code: 'America/Argentina/Mendoza', name: '门多萨' },
            { code: 'America/Argentina/Rio_Gallegos', name: '里约加列戈斯' },
            { code: 'America/Argentina/Salta', name: '萨尔塔' },
            { code: 'America/Argentina/San_Juan', name: '圣胡安' },
            { code: 'America/Argentina/San_Luis', name: '圣路易斯' },
            { code: 'America/Argentina/Tucuman', name: '图库曼' },
            { code: 'America/Argentina/Ushuaia', name: '乌斯怀亚' },
            { code: 'America/Asuncion', name: '亚松森' },
            { code: 'America/Atikokan', name: '阿提科坎' },
            { code: 'America/Bahia_Banderas', name: '班德拉斯湾' },
            { code: 'America/Bahia', name: '巴伊亚' },
            { code: 'America/Barbados', name: '巴巴多斯' },
            { code: 'America/Belem', name: '贝伦' },
            { code: 'America/Belize', name: '伯利兹' },
            { code: 'America/Blanc-Sablon', name: '布兰科萨布隆' },
            { code: 'America/Boa_Vista', name: '博阿维斯塔岛' },
            { code: 'America/Bogota', name: '波哥大' },
            { code: 'America/Boise', name: '博伊西' },
            { code: 'America/Cambridge_Bay', name: '剑桥湾' },
            { code: 'America/Campo_Grande', name: '坎普格兰德' },
            { code: 'America/Cancun', name: '坎昆' },
            { code: 'America/Caracas', name: '加拉加斯' },
            { code: 'America/Cayenne', name: '卡宴' },
            { code: 'America/Chicago', name: '芝加哥' },
            { code: 'America/Chihuahua', name: '奇瓦瓦' },
            { code: 'America/Costa_Rica', name: '哥斯达黎加' },
            { code: 'America/Creston', name: '克雷斯顿' },
            { code: 'America/Cuiaba', name: '库亚巴' },
            { code: 'America/Curacao', name: '库拉索' },
            { code: 'America/Danmarkshavn', name: '丹麦' },
            { code: 'America/Dawson_Creek', name: '道森溪' },
            { code: 'America/Dawson', name: '道森' },
            { code: 'America/Denver', name: '丹佛' },
            { code: 'America/Detroit', name: '底特律' },
            { code: 'America/Edmonton', name: '埃德蒙顿' },
            { code: 'America/Eirunepe', name: '埃鲁内佩' },
            { code: 'America/El_Salvador', name: '萨尔瓦多' },
            { code: 'America/Fort_Nelson', name: '纳尔逊堡' },
            { code: 'America/Fortaleza', name: '要塞' },
            { code: 'America/Glace_Bay', name: '格拉斯湾' },
            { code: 'America/Godthab', name: '哥达布' },
            { code: 'America/Goose_Bay', name: '鹅湾' },
            { code: 'America/Grand_Turk', name: '大土耳其人' },
            { code: 'America/Guatemala', name: '危地马拉' },
            { code: 'America/Guayaquil', name: '瓜亚基尔' },
            { code: 'America/Guyana', name: '圭亚那' },
            { code: 'America/Halifax', name: '哈利法克斯' },
            { code: 'America/Havana', name: '哈瓦那' },
            { code: 'America/Hermosillo', name: '赫莫西洛' },
            { code: 'America/Indiana/Indianapolis', name: '印第安纳/印第安纳波利斯' },
            { code: 'America/Indiana/Knox', name: '印第安纳/诺克斯' },
            { code: 'America/Indiana/Marengo', name: '印第安纳/马伦戈' },
            { code: 'America/Indiana/Petersburg', name: '印第安纳/彼得堡' },
            { code: 'America/Indiana/Tell_City', name: '印第安纳/泰尔城' },
            { code: 'America/Indiana/Vevay', name: '印第安纳/维维' },
            { code: 'America/Indiana/Vincennes', name: '印第安纳/文森' },
            { code: 'America/Indiana/Winamac', name: '印第安纳/维那马克' },
            { code: 'America/Inuvik', name: '因努维克' },
            { code: 'America/Iqaluit', name: '伊卡卢伊特' },
            { code: 'America/Jamaica', name: '牙买加' },
            { code: 'America/Juneau', name: '朱诺' },
            { code: 'America/Kentucky/Louisville', name: '肯塔基州/路易斯维尔' },
            { code: 'America/Kentucky/Monticello', name: '肯塔基州/蒙蒂塞洛' },
            { code: 'America/La_Paz', name: '拉巴斯' },
            { code: 'America/Lima', name: '利马' },
            { code: 'America/Los_Angeles', name: '洛杉矶' },
            { code: 'America/Maceio', name: '马塞奥' },
            { code: 'America/Managua', name: '马那瓜' },
            { code: 'America/Manaus', name: '马瑙斯' },
            { code: 'America/Martinique', name: '马提尼克' },
            { code: 'America/Matamoros', name: '马塔莫罗斯' },
            { code: 'America/Mazatlan', name: '马萨特兰' },
            { code: 'America/Menominee', name: '美诺米尼' },
            { code: 'America/Merida', name: '梅里达' },
            { code: 'America/Metlakatla', name: '梅特拉卡特拉' },
            { code: 'America/Mexico_City', name: '墨西哥城' },
            { code: 'America/Miquelon', name: '密克隆' },
            { code: 'America/Moncton', name: '蒙克顿' },
            { code: 'America/Monterrey', name: '蒙特雷' },
            { code: 'America/Montevideo', name: '蒙得维的亚' },
            { code: 'America/Nassau', name: '拿骚' },
            { code: 'America/New_York', name: '纽约' },
            { code: 'America/Nipigon', name: '尼皮翁' },
            { code: 'America/Nome', name: '诺姆' },
            { code: 'America/Noronha', name: '诺罗尼亚' },
            { code: 'America/North_Dakota/Beulah', name: '北达科他州/贝乌拉' },
            { code: 'America/North_Dakota/Center', name: '北达科他州/森特' },
            { code: 'America/North_Dakota/New_Salem', name: '北达科他州/新塞勒姆' },
            { code: 'America/Ojinaga', name: '奥希纳加' },
            { code: 'America/Panama', name: '巴拿马' },
            { code: 'America/Pangnirtung', name: '庞尼东' },
            { code: 'America/Paramaribo', name: '帕拉马里博' },
            { code: 'America/Phoenix', name: '凤凰城' },
            { code: 'America/Port_of_Spain', name: '西班牙港' },
            { code: 'America/Port-au-Prince', name: '太子港' },
            { code: 'America/Porto_Velho', name: '维略港' },
            { code: 'America/Puerto_Rico', name: '波多黎各' },
            { code: 'America/Punta_Arenas', name: '蓬塔竞技场' },
            { code: 'America/Rainy_River', name: '多雨河' },
            { code: 'America/Rankin_Inlet', name: '兰金海湾' },
            { code: 'America/Recife', name: '累西腓' },
            { code: 'America/Regina', name: '里贾纳' },
            { code: 'America/Resolute', name: '雷索卢特' },
            { code: 'America/Rio_Branco', name: '里约布兰科' },
            { code: 'America/Santarem', name: '桑塔雷姆' },
            { code: 'America/Santiago', name: '圣地亚哥' },
            { code: 'America/Santo_Domingo', name: '圣多明各' },
            { code: 'America/Sao_Paulo', name: '圣保罗' },
            { code: 'America/Scoresbysund', name: '瑟莫苏克' },
            { code: 'America/Sitka', name: '锡特卡' },
            { code: 'America/St_Johns', name: '圣约翰' },
            { code: 'America/Swift_Current', name: '斯威夫特卡伦特' },
            { code: 'America/Tegucigalpa', name: '特古西加尔巴' },
            { code: 'America/Thule', name: '图勒' },
            { code: 'America/Thunder_Bay', name: '雷霆湾' },
            { code: 'America/Tijuana', name: '蒂华纳' },
            { code: 'America/Toronto', name: '多伦多' },
            { code: 'America/Vancouver', name: '温哥华' },
            { code: 'America/Whitehorse', name: '怀特霍斯' },
            { code: 'America/Winnipeg', name: '温尼伯' },
            { code: 'America/Yakutat', name: '雅库塔' },
            { code: 'America/Yellowknife', name: '耶洛奈夫' },
        ]
    },
    {
        zone: { code: 'Antarctica', name: '南极洲' },
        region: [
            { code: 'Antarctica/Casey', name: '凯西' },
            { code: 'Antarctica/Davis', name: '戴维斯' },
            { code: 'Antarctica/DumontDUrville', name: '杜蒙杜维尔' },
            { code: 'Antarctica/Macquarie', name: '麦格理亚' },
            { code: 'Antarctica/Mawson', name: '莫森站' },
            { code: 'Antarctica/Palmer', name: '帕尔默' },
            { code: 'Antarctica/Rothera', name: '罗瑟拉' },
            { code: 'Antarctica/Syowa', name: '西瓦' },
            { code: 'Antarctica/Troll', name: '巨魔' },
            { code: 'Antarctica/Vostok', name: '沃斯托克' },
        ]
    }, {
        zone: { code: 'Asia', name: '亚洲' },
        region: [
            { code: 'Asia/Almaty', name: '阿拉木图' },
            { code: 'Asia/Amman', name: '安曼' },
            { code: 'Asia/Anadyr', name: '阿纳德尔' },
            { code: 'Asia/Aqtau', name: '阿克套' },
            { code: 'Asia/Aqtobe', name: '阿克托贝' },
            { code: 'Asia/Ashgabat', name: '阿什哈巴德' },
            { code: 'Asia/Atyrau', name: '阿特劳' },
            { code: 'Asia/Baghdad', name: '巴格达' },
            { code: 'Asia/Baku', name: '巴库' },
            { code: 'Asia/Bangkok', name: '曼谷' },
            { code: 'Asia/Barnaul', name: '巴诺' },
            { code: 'Asia/Beirut', name: '贝鲁特' },
            { code: 'Asia/Bishkek', name: '比什凯克' },
            { code: 'Asia/Brunei', name: '文莱' },
            { code: 'Asia/Chita', name: '赤塔' },
            { code: 'Asia/Choibalsan', name: '乔巴山' },
            { code: 'Asia/Colombo', name: '科伦坡' },
            { code: 'Asia/Damascus', name: '大马士革' },
            { code: 'Asia/Dhaka', name: '达卡' },
            { code: 'Asia/Dili', name: '帝力' },
            { code: 'Asia/Dubai', name: '迪拜' },
            { code: 'Asia/Dushanbe', name: '杜尚别' },
            { code: 'Asia/Famagusta', name: '法马古斯塔' },
            { code: 'Asia/Gaza', name: '加沙' },
            { code: 'Asia/Hebron', name: '希布伦' },
            { code: 'Asia/Ho_Chi_Minh', name: '胡志明' },
            { code: 'Asia/Hong_Kong', name: '香港' },
            { code: 'Asia/Hovd', name: '科布多城' },
            { code: 'Asia/Irkutsk', name: '伊尔库茨克' },
            { code: 'Asia/Jakarta', name: '雅加达' },
            { code: 'Asia/Jayapura', name: '加雅布拉' },
            { code: 'Asia/Jerusalem', name: '耶路撒冷' },
            { code: 'Asia/Kabul', name: '喀布尔' },
            { code: 'Asia/Kamchatka', name: '堪察加半岛' },
            { code: 'Asia/Karachi', name: '卡拉奇' },
            { code: 'Asia/Kathmandu', name: '加德满都' },
            { code: 'Asia/Khandyga', name: '坎迪加' },
            { code: 'Asia/Kolkata', name: '加尔各答' },
            { code: 'Asia/Krasnoyarsk', name: '克拉斯诺亚尔斯克' },
            { code: 'Asia/Kuala_Lumpur', name: '吉隆坡' },
            { code: 'Asia/Kuching', name: '古晋' },
            { code: 'Asia/Macau', name: '澳门' },
            { code: 'Asia/Magadan', name: '马加丹' },
            { code: 'Asia/Makassar', name: '马卡萨' },
            { code: 'Asia/Manila', name: '马尼拉' },
            { code: 'Asia/Nicosia', name: '尼科西亚' },
            { code: 'Asia/Novokuznetsk', name: '新库兹涅茨克' },
            { code: 'Asia/Novosibirsk', name: '新西伯利亚' },
            { code: 'Asia/Omsk', name: '鄂木斯克' },
            { code: 'Asia/Oral', name: '乌拉尔' },
            { code: 'Asia/Pontianak', name: '庞蒂亚纳克' },
            { code: 'Asia/Pyongyang', name: '平壤' },
            { code: 'Asia/Qatar', name: '卡塔尔' },
            { code: 'Asia/Qostanay', name: '库斯塔奈' },
            { code: 'Asia/Qyzylorda', name: '克孜勒奥尔达' },
            { code: 'Asia/Riyadh', name: '利雅得' },
            { code: 'Asia/Sakhalin', name: '萨哈林' },
            { code: 'Asia/Samarkand', name: '撒马尔罕' },
            { code: 'Asia/Seoul', name: '首尔' },
            { code: 'Asia/Shanghai', name: '上海' },
            { code: 'Asia/Singapore', name: '新加坡' },
            { code: 'Asia/Srednekolymsk', name: '哥伦比亚中部' },
            { code: 'Asia/Taipei', name: '台北' },
            { code: 'Asia/Tashkent', name: '塔什干' },
            { code: 'Asia/Tbilisi', name: '第比利斯' },
            { code: 'Asia/Tehran', name: '德黑兰' },
            { code: 'Asia/Thimphu', name: '廷布' },
            { code: 'Asia/Tokyo', name: '东京' },
            { code: 'Asia/Tomsk', name: '托木斯克' },
            { code: 'Asia/Ulaanbaatar', name: '乌兰巴托' },
            { code: 'Asia/Urumqi', name: '乌鲁木齐' },
            { code: 'Asia/Ust-Nera', name: '乌斯季涅拉' },
            { code: 'Asia/Vladivostok', name: '海参崴' },
            { code: 'Asia/Yakutsk', name: '雅库茨克' },
            { code: 'Asia/Yangon', name: '仰光' },
            { code: 'Asia/Yekaterinburg', name: '叶卡捷琳堡' },
            { code: 'Asia/Yerevan', name: '埃里温' },
        ]
    }, {
        zone: { code: 'Atlantic', name: '大西洋' },
        region: [
            { code: 'Atlantic/Azores', name: '亚速尔群岛' },
            { code: 'Atlantic/Bermuda', name: '百慕大' },
            { code: 'Atlantic/Canary', name: '金丝雀' },
            { code: 'Atlantic/Cape_Verde', name: '佛得角' },
            { code: 'Atlantic/Faroe', name: '法罗' },
            { code: 'Atlantic/Madeira', name: '马德拉' },
            { code: 'Atlantic/Reykjavik', name: '雷克雅未克' },
            { code: 'Atlantic/South_Georgia', name: '南乔治亚' },
            { code: 'Atlantic/Stanley', name: '斯坦利' },
        ]
    }, {
        zone: { code: 'Australia', name: '澳洲' },
        region: [
            { code: 'Australia/Adelaide', name: '阿德莱德' },
            { code: 'Australia/Brisbane', name: '布里斯班' },
            { code: 'Australia/Broken_Hill', name: '布罗克山' },
            { code: 'Australia/Currie', name: '咖喱' },
            { code: 'Australia/Darwin', name: '达尔文' },
            { code: 'Australia/Eucla', name: '尤克拉' },
            { code: 'Australia/Hobart', name: '霍巴特' },
            { code: 'Australia/Lindeman', name: '林德曼' },
            { code: 'Australia/Lord_Howe', name: '豪勋爵' },
            { code: 'Australia/Melbourne', name: '墨尔本' },
            { code: 'Australia/Perth', name: '珀斯' },
            { code: 'Australia/Sydney', name: '悉尼' },
        ]
    }, {
        zone: { code: 'Europe', name: '欧洲' },
        region: [
            { code: 'Europe/Amsterdam', name: '阿姆斯特丹' },
            { code: 'Europe/Andorra', name: '安道尔' },
            { code: 'Europe/Astrakhan', name: '阿斯特拉罕' },
            { code: 'Europe/Athens', name: '雅典' },
            { code: 'Europe/Belgrade', name: '贝尔格莱德' },
            { code: 'Europe/Berlin', name: '柏林' },
            { code: 'Europe/Brussels', name: '布鲁塞尔' },
            { code: 'Europe/Bucharest', name: '布加勒斯特' },
            { code: 'Europe/Budapest', name: '布达佩斯' },
            { code: 'Europe/Chisinau', name: '基希讷乌' },
            { code: 'Europe/Copenhagen', name: '哥本哈根' },
            { code: 'Europe/Dublin', name: '都柏林' },
            { code: 'Europe/Gibraltar', name: '直布罗陀' },
            { code: 'Europe/Helsinki', name: '赫尔辛基' },
            { code: 'Europe/Istanbul', name: '伊斯坦布尔' },
            { code: 'Europe/Kaliningrad', name: '加里宁格勒' },
            { code: 'Europe/Kiev', name: '基辅' },
            { code: 'Europe/Kirov', name: '基洛夫' },
            { code: 'Europe/Lisbon', name: '里斯本' },
            { code: 'Europe/London', name: '伦敦' },
            { code: 'Europe/Luxembourg', name: '卢森堡' },
            { code: 'Europe/Madrid', name: '马德里' },
            { code: 'Europe/Malta', name: '马耳他' },
            { code: 'Europe/Minsk', name: '明斯克' },
            { code: 'Europe/Monaco', name: '摩纳哥' },
            { code: 'Europe/Moscow', name: '莫斯科' },
            { code: 'Europe/Oslo', name: '奥斯陆' },
            { code: 'Europe/Paris', name: '巴黎' },
            { code: 'Europe/Prague', name: '布拉格' },
            { code: 'Europe/Riga', name: '里加' },
            { code: 'Europe/Rome', name: '罗马' },
            { code: 'Europe/Samara', name: '萨马拉' },
            { code: 'Europe/Saratov', name: '萨拉托夫' },
            { code: 'Europe/Simferopol', name: '辛菲罗波尔' },
            { code: 'Europe/Sofia', name: '索非亚' },
            { code: 'Europe/Stockholm', name: '斯德哥尔摩' },
            { code: 'Europe/Tallinn', name: '塔林' },
            { code: 'Europe/Tirane', name: '泰兰' },
            { code: 'Europe/Ulyanovsk', name: '乌里扬诺夫斯克' },
            { code: 'Europe/Uzhgorod', name: '乌日哥罗德' },
            { code: 'Europe/Vienna', name: '维也纳' },
            { code: 'Europe/Vilnius', name: '维尔纽斯' },
            { code: 'Europe/Volgograd', name: '伏尔加格勒' },
            { code: 'Europe/Warsaw', name: '华沙' },
            { code: 'Europe/Zaporozhye', name: '扎波罗齐' },
            { code: 'Europe/Zurich', name: '苏黎世' },
        ]
    }, {
        zone: { code: 'Indian', name: '印度洋' },
        region: [
            { code: 'Indian/Chagos', name: '查戈斯' },
            { code: 'Indian/Christmas', name: '圣诞节' },
            { code: 'Indian/Cocos', name: '科科斯' },
            { code: 'Indian/Kerguelen', name: '凯尔盖朗' },
            { code: 'Indian/Mahe', name: '马埃' },
            { code: 'Indian/Maldives', name: '马尔代夫' },
            { code: 'Indian/Mauritius', name: '毛里求斯' },
            { code: 'Indian/Reunion', name: '留尼汪' },
        ]
    }, {
        zone: { code: 'Pacific', name: '太平洋' },
        region: [
            { code: 'Pacific/Apia', name: '阿皮亚' },
            { code: 'Pacific/Auckland', name: '奥克兰' },
            { code: 'Pacific/Bougainville', name: '布干维尔' },
            { code: 'Pacific/Chatham', name: '查塔姆' },
            { code: 'Pacific/Chuuk', name: '丘克' },
            { code: 'Pacific/Easter', name: '复活节' },
            { code: 'Pacific/Efate', name: '埃法特' },
            { code: 'Pacific/Enderbury', name: '恩德伯里' },
            { code: 'Pacific/Fakaofo', name: '法考福' },
            { code: 'Pacific/Fiji', name: '斐济' },
            { code: 'Pacific/Funafuti', name: '富纳富提' },
            { code: 'Pacific/Galapagos', name: '加拉帕戈斯' },
            { code: 'Pacific/Gambier', name: '冈比亚' },
            { code: 'Pacific/Guadalcanal', name: '瓜达尔卡纳尔' },
            { code: 'Pacific/Guam', name: '关岛' },
            { code: 'Pacific/Honolulu', name: '檀香山' },
            { code: 'Pacific/Kiritimati', name: '基里提马提' },
            { code: 'Pacific/Kosrae', name: '科斯雷' },
            { code: 'Pacific/Kwajalein', name: '夸贾林' },
            { code: 'Pacific/Majuro', name: '马朱罗' },
            { code: 'Pacific/Marquesas', name: '马尔克斯' },
            { code: 'Pacific/Nauru', name: '瑙鲁' },
            { code: 'Pacific/Niue', name: '纽埃' },
            { code: 'Pacific/Norfolk', name: '诺福克' },
            { code: 'Pacific/Noumea', name: '努美阿' },
            { code: 'Pacific/Pago_Pago', name: '帕果帕果' },
            { code: 'Pacific/Palau', name: '帕劳' },
            { code: 'Pacific/Pitcairn', name: '皮特凯恩' },
            { code: 'Pacific/Pohnpei', name: '波恩佩' },
            { code: 'Pacific/Port_Moresby', name: '莫尔兹比港' },
            { code: 'Pacific/Rarotonga', name: '拉罗通加' },
            { code: 'Pacific/Tahiti', name: '大溪地' },
            { code: 'Pacific/Tarawa', name: '塔拉瓦' },
            { code: 'Pacific/Tongatapu', name: '汤加塔普' },
            { code: 'Pacific/Wake', name: '威克' },
            { code: 'Pacific/Wallis', name: '瓦利斯' },
        ]
    },
]

export const allTimeZones = [
    'Africa/Abidjan',
    'Africa/Accra',
    'Africa/Algiers',
    'Africa/Bissau',
    'Africa/Cairo',
    'Africa/Casablanca',
    'Africa/Ceuta',
    'Africa/El_Aaiun',
    'Africa/Johannesburg',
    'Africa/Juba',
    'Africa/Khartoum',
    'Africa/Lagos',
    'Africa/Maputo',
    'Africa/Monrovia',
    'Africa/Nairobi',
    'Africa/Ndjamena',
    'Africa/Sao_Tome',
    'Africa/Tripoli',
    'Africa/Tunis',
    'Africa/Windhoek',
    'America/Adak',
    'America/Anchorage',
    'America/Araguaina',
    'America/Argentina/Buenos_Aires',
    'America/Argentina/Catamarca',
    'America/Argentina/Cordoba',
    'America/Argentina/Jujuy',
    'America/Argentina/La_Rioja',
    'America/Argentina/Mendoza',
    'America/Argentina/Rio_Gallegos',
    'America/Argentina/Salta',
    'America/Argentina/San_Juan',
    'America/Argentina/San_Luis',
    'America/Argentina/Tucuman',
    'America/Argentina/Ushuaia',
    'America/Asuncion',
    'America/Atikokan',
    'America/Bahia_Banderas',
    'America/Bahia',
    'America/Barbados',
    'America/Belem',
    'America/Belize',
    'America/Blanc-Sablon',
    'America/Boa_Vista',
    'America/Bogota',
    'America/Boise',
    'America/Cambridge_Bay',
    'America/Campo_Grande',
    'America/Cancun',
    'America/Caracas',
    'America/Cayenne',
    'America/Chicago',
    'America/Chihuahua',
    'America/Costa_Rica',
    'America/Creston',
    'America/Cuiaba',
    'America/Curacao',
    'America/Danmarkshavn',
    'America/Dawson_Creek',
    'America/Dawson',
    'America/Denver',
    'America/Detroit',
    'America/Edmonton',
    'America/Eirunepe',
    'America/El_Salvador',
    'America/Fort_Nelson',
    'America/Fortaleza',
    'America/Glace_Bay',
    'America/Godthab',
    'America/Goose_Bay',
    'America/Grand_Turk',
    'America/Guatemala',
    'America/Guayaquil',
    'America/Guyana',
    'America/Halifax',
    'America/Havana',
    'America/Hermosillo',
    'America/Indiana/Indianapolis',
    'America/Indiana/Knox',
    'America/Indiana/Marengo',
    'America/Indiana/Petersburg',
    'America/Indiana/Tell_City',
    'America/Indiana/Vevay',
    'America/Indiana/Vincennes',
    'America/Indiana/Winamac',
    'America/Inuvik',
    'America/Iqaluit',
    'America/Jamaica',
    'America/Juneau',
    'America/Kentucky/Louisville',
    'America/Kentucky/Monticello',
    'America/La_Paz',
    'America/Lima',
    'America/Los_Angeles',
    'America/Maceio',
    'America/Managua',
    'America/Manaus',
    'America/Martinique',
    'America/Matamoros',
    'America/Mazatlan',
    'America/Menominee',
    'America/Merida',
    'America/Metlakatla',
    'America/Mexico_City',
    'America/Miquelon',
    'America/Moncton',
    'America/Monterrey',
    'America/Montevideo',
    'America/Nassau',
    'America/New_York',
    'America/Nipigon',
    'America/Nome',
    'America/Noronha',
    'America/North_Dakota/Beulah',
    'America/North_Dakota/Center',
    'America/North_Dakota/New_Salem',
    'America/Ojinaga',
    'America/Panama',
    'America/Pangnirtung',
    'America/Paramaribo',
    'America/Phoenix',
    'America/Port_of_Spain',
    'America/Port-au-Prince',
    'America/Porto_Velho',
    'America/Puerto_Rico',
    'America/Punta_Arenas',
    'America/Rainy_River',
    'America/Rankin_Inlet',
    'America/Recife',
    'America/Regina',
    'America/Resolute',
    'America/Rio_Branco',
    'America/Santarem',
    'America/Santiago',
    'America/Santo_Domingo',
    'America/Sao_Paulo',
    'America/Scoresbysund',
    'America/Sitka',
    'America/St_Johns',
    'America/Swift_Current',
    'America/Tegucigalpa',
    'America/Thule',
    'America/Thunder_Bay',
    'America/Tijuana',
    'America/Toronto',
    'America/Vancouver',
    'America/Whitehorse',
    'America/Winnipeg',
    'America/Yakutat',
    'America/Yellowknife',
    'Antarctica/Casey',
    'Antarctica/Davis',
    'Antarctica/DumontDUrville',
    'Antarctica/Macquarie',
    'Antarctica/Mawson',
    'Antarctica/Palmer',
    'Antarctica/Rothera',
    'Antarctica/Syowa',
    'Antarctica/Troll',
    'Antarctica/Vostok',
    'Asia/Almaty',
    'Asia/Amman',
    'Asia/Anadyr',
    'Asia/Aqtau',
    'Asia/Aqtobe',
    'Asia/Ashgabat',
    'Asia/Atyrau',
    'Asia/Baghdad',
    'Asia/Baku',
    'Asia/Bangkok',
    'Asia/Barnaul',
    'Asia/Beirut',
    'Asia/Bishkek',
    'Asia/Brunei',
    'Asia/Chita',
    'Asia/Choibalsan',
    'Asia/Colombo',
    'Asia/Damascus',
    'Asia/Dhaka',
    'Asia/Dili',
    'Asia/Dubai',
    'Asia/Dushanbe',
    'Asia/Famagusta',
    'Asia/Gaza',
    'Asia/Hebron',
    'Asia/Ho_Chi_Minh',
    'Asia/Hong_Kong',
    'Asia/Hovd',
    'Asia/Irkutsk',
    'Asia/Jakarta',
    'Asia/Jayapura',
    'Asia/Jerusalem',
    'Asia/Kabul',
    'Asia/Kamchatka',
    'Asia/Karachi',
    'Asia/Kathmandu',
    'Asia/Khandyga',
    'Asia/Kolkata',
    'Asia/Krasnoyarsk',
    'Asia/Kuala_Lumpur',
    'Asia/Kuching',
    'Asia/Macau',
    'Asia/Magadan',
    'Asia/Makassar',
    'Asia/Manila',
    'Asia/Nicosia',
    'Asia/Novokuznetsk',
    'Asia/Novosibirsk',
    'Asia/Omsk',
    'Asia/Oral',
    'Asia/Pontianak',
    'Asia/Pyongyang',
    'Asia/Qatar',
    'Asia/Qostanay',
    'Asia/Qyzylorda',
    'Asia/Riyadh',
    'Asia/Sakhalin',
    'Asia/Samarkand',
    'Asia/Seoul',
    'Asia/Shanghai',
    'Asia/Singapore',
    'Asia/Srednekolymsk',
    'Asia/Taipei',
    'Asia/Tashkent',
    'Asia/Tbilisi',
    'Asia/Tehran',
    'Asia/Thimphu',
    'Asia/Tokyo',
    'Asia/Tomsk',
    'Asia/Ulaanbaatar',
    'Asia/Urumqi',
    'Asia/Ust-Nera',
    'Asia/Vladivostok',
    'Asia/Yakutsk',
    'Asia/Yangon',
    'Asia/Yekaterinburg',
    'Asia/Yerevan',
    'Atlantic/Azores',
    'Atlantic/Bermuda',
    'Atlantic/Canary',
    'Atlantic/Cape_Verde',
    'Atlantic/Faroe',
    'Atlantic/Madeira',
    'Atlantic/Reykjavik',
    'Atlantic/South_Georgia',
    'Atlantic/Stanley',
    'Australia/Adelaide',
    'Australia/Brisbane',
    'Australia/Broken_Hill',
    'Australia/Currie',
    'Australia/Darwin',
    'Australia/Eucla',
    'Australia/Hobart',
    'Australia/Lindeman',
    'Australia/Lord_Howe',
    'Australia/Melbourne',
    'Australia/Perth',
    'Australia/Sydney',
    'Europe/Amsterdam',
    'Europe/Andorra',
    'Europe/Astrakhan',
    'Europe/Athens',
    'Europe/Belgrade',
    'Europe/Berlin',
    'Europe/Brussels',
    'Europe/Bucharest',
    'Europe/Budapest',
    'Europe/Chisinau',
    'Europe/Copenhagen',
    'Europe/Dublin',
    'Europe/Gibraltar',
    'Europe/Helsinki',
    'Europe/Istanbul',
    'Europe/Kaliningrad',
    'Europe/Kiev',
    'Europe/Kirov',
    'Europe/Lisbon',
    'Europe/London',
    'Europe/Luxembourg',
    'Europe/Madrid',
    'Europe/Malta',
    'Europe/Minsk',
    'Europe/Monaco',
    'Europe/Moscow',
    'Europe/Oslo',
    'Europe/Paris',
    'Europe/Prague',
    'Europe/Riga',
    'Europe/Rome',
    'Europe/Samara',
    'Europe/Saratov',
    'Europe/Simferopol',
    'Europe/Sofia',
    'Europe/Stockholm',
    'Europe/Tallinn',
    'Europe/Tirane',
    'Europe/Ulyanovsk',
    'Europe/Uzhgorod',
    'Europe/Vienna',
    'Europe/Vilnius',
    'Europe/Volgograd',
    'Europe/Warsaw',
    'Europe/Zaporozhye',
    'Europe/Zurich',
    'Indian/Chagos',
    'Indian/Christmas',
    'Indian/Cocos',
    'Indian/Kerguelen',
    'Indian/Mahe',
    'Indian/Maldives',
    'Indian/Mauritius',
    'Indian/Reunion',
    'Pacific/Apia',
    'Pacific/Auckland',
    'Pacific/Bougainville',
    'Pacific/Chatham',
    'Pacific/Chuuk',
    'Pacific/Easter',
    'Pacific/Efate',
    'Pacific/Enderbury',
    'Pacific/Fakaofo',
    'Pacific/Fiji',
    'Pacific/Funafuti',
    'Pacific/Galapagos',
    'Pacific/Gambier',
    'Pacific/Guadalcanal',
    'Pacific/Guam',
    'Pacific/Honolulu',
    'Pacific/Kiritimati',
    'Pacific/Kosrae',
    'Pacific/Kwajalein',
    'Pacific/Majuro',
    'Pacific/Marquesas',
    'Pacific/Nauru',
    'Pacific/Niue',
    'Pacific/Norfolk',
    'Pacific/Noumea',
    'Pacific/Pago_Pago',
    'Pacific/Palau',
    'Pacific/Pitcairn',
    'Pacific/Pohnpei',
    'Pacific/Port_Moresby',
    'Pacific/Rarotonga',
    'Pacific/Tahiti',
    'Pacific/Tarawa',
    'Pacific/Tongatapu',
    'Pacific/Wake',
    'Pacific/Wallis',
];
